baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Jane Doe"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "LUA  "
author = "Umut Avcı"
#copyright = "2020-2021"
description = "Software & Design"
profilePicture = "/img/new.png"
keywords = "Software , "
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/umutavc%C4%B1/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/mrrumutt2"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/mrrumutt2"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@alexbilz.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Anasayfa"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Hakkımda"
  weight = 300
  identifier = "about"
  url = "/about/"


  [[menu.main]]
  name = "Bana Ulaş"
  weight = 400
  identifier = "contact"
  url = "/contact/"


 [[menu.main]]
  name = "Projelerim"
  weight = 400
  identifier = "proje"
  url = "/proje/"

  [[menu.main]]
  name = "Yazılım"
  weight = 400
  identifier = "yazılım"
  url = "/yazılım/"

  [[menu.main]]
  name = "Tasarım"
  weight = 400
  identifier = "tasarım"
  url = "/tasarım/"

